server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /health {
    return 200 "ok";
}
    

    location /api/ {
        # Using the direct VM Private IP
        proxy_pass http://10.0.2.4:8080;
        
        # Performance & Stability Headers
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # BIG TIMEOUTS: Fixes the 504 Gateway Timeout
        # Sometimes the internal VNet jump takes a second; 
        # this tells Nginx to stay on the line for 5 minutes.
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;

        proxy_buffering off;
        
        # Prevent Nginx from failing over or marking the VM as "down"
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
    }
}